// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef PROTOBUF_Message_2eproto__INCLUDED
#define PROTOBUF_Message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Message_2eproto();
void protobuf_AssignDesc_Message_2eproto();
void protobuf_ShutdownFile_Message_2eproto();

class MSG_HeartBeat_SYN;
class MSG_HeartBeat_ACK;

enum MESSAGEID {
  HEARTBEAT_SYN = 0,
  HEARTBEAT_ACK = 1
};
bool MESSAGEID_IsValid(int value);
const MESSAGEID MESSAGEID_MIN = HEARTBEAT_SYN;
const MESSAGEID MESSAGEID_MAX = HEARTBEAT_ACK;
const int MESSAGEID_ARRAYSIZE = MESSAGEID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MESSAGEID_descriptor();
inline const ::std::string& MESSAGEID_Name(MESSAGEID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MESSAGEID_descriptor(), value);
}
inline bool MESSAGEID_Parse(
    const ::std::string& name, MESSAGEID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MESSAGEID>(
    MESSAGEID_descriptor(), name, value);
}
// ===================================================================

class MSG_HeartBeat_SYN : public ::google::protobuf::Message {
 public:
  MSG_HeartBeat_SYN();
  virtual ~MSG_HeartBeat_SYN();

  MSG_HeartBeat_SYN(const MSG_HeartBeat_SYN& from);

  inline MSG_HeartBeat_SYN& operator=(const MSG_HeartBeat_SYN& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_HeartBeat_SYN& default_instance();

  void Swap(MSG_HeartBeat_SYN* other);

  // implements Message ----------------------------------------------

  MSG_HeartBeat_SYN* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_HeartBeat_SYN& from);
  void MergeFrom(const MSG_HeartBeat_SYN& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_SYN];
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 1;
  inline ::MESSAGEID msgid() const;
  inline void set_msgid(::MESSAGEID value);

  // @@protoc_insertion_point(class_scope:MSG_HeartBeat_SYN)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int msgid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static MSG_HeartBeat_SYN* default_instance_;
};
// -------------------------------------------------------------------

class MSG_HeartBeat_ACK : public ::google::protobuf::Message {
 public:
  MSG_HeartBeat_ACK();
  virtual ~MSG_HeartBeat_ACK();

  MSG_HeartBeat_ACK(const MSG_HeartBeat_ACK& from);

  inline MSG_HeartBeat_ACK& operator=(const MSG_HeartBeat_ACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_HeartBeat_ACK& default_instance();

  void Swap(MSG_HeartBeat_ACK* other);

  // implements Message ----------------------------------------------

  MSG_HeartBeat_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_HeartBeat_ACK& from);
  void MergeFrom(const MSG_HeartBeat_ACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_ACK];
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgidFieldNumber = 1;
  inline ::MESSAGEID msgid() const;
  inline void set_msgid(::MESSAGEID value);

  // @@protoc_insertion_point(class_scope:MSG_HeartBeat_ACK)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int msgid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Message_2eproto();
  friend void protobuf_AssignDesc_Message_2eproto();
  friend void protobuf_ShutdownFile_Message_2eproto();

  void InitAsDefaultInstance();
  static MSG_HeartBeat_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_HeartBeat_SYN

// optional .MESSAGEID msgid = 1 [default = HEARTBEAT_SYN];
inline bool MSG_HeartBeat_SYN::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_HeartBeat_SYN::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_HeartBeat_SYN::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_HeartBeat_SYN::clear_msgid() {
  msgid_ = 0;
  clear_has_msgid();
}
inline ::MESSAGEID MSG_HeartBeat_SYN::msgid() const {
  return static_cast< ::MESSAGEID >(msgid_);
}
inline void MSG_HeartBeat_SYN::set_msgid(::MESSAGEID value) {
  assert(::MESSAGEID_IsValid(value));
  set_has_msgid();
  msgid_ = value;
}

// -------------------------------------------------------------------

// MSG_HeartBeat_ACK

// optional .MESSAGEID msgid = 1 [default = HEARTBEAT_ACK];
inline bool MSG_HeartBeat_ACK::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_HeartBeat_ACK::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_HeartBeat_ACK::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_HeartBeat_ACK::clear_msgid() {
  msgid_ = 1;
  clear_has_msgid();
}
inline ::MESSAGEID MSG_HeartBeat_ACK::msgid() const {
  return static_cast< ::MESSAGEID >(msgid_);
}
inline void MSG_HeartBeat_ACK::set_msgid(::MESSAGEID value) {
  assert(::MESSAGEID_IsValid(value));
  set_has_msgid();
  msgid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MESSAGEID>() {
  return ::MESSAGEID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Message_2eproto__INCLUDED
