// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MSG_HeartBeat_SYN_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_HeartBeat_SYN_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSG_HeartBeat_ACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_HeartBeat_ACK_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MESSAGEID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Message_2eproto() {
  protobuf_AddDesc_Message_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Message.proto");
  GOOGLE_CHECK(file != NULL);
  MSG_HeartBeat_SYN_descriptor_ = file->message_type(0);
  static const int MSG_HeartBeat_SYN_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_HeartBeat_SYN, msgid_),
  };
  MSG_HeartBeat_SYN_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_HeartBeat_SYN_descriptor_,
      MSG_HeartBeat_SYN::default_instance_,
      MSG_HeartBeat_SYN_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_HeartBeat_SYN, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_HeartBeat_SYN, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_HeartBeat_SYN));
  MSG_HeartBeat_ACK_descriptor_ = file->message_type(1);
  static const int MSG_HeartBeat_ACK_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_HeartBeat_ACK, msgid_),
  };
  MSG_HeartBeat_ACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_HeartBeat_ACK_descriptor_,
      MSG_HeartBeat_ACK::default_instance_,
      MSG_HeartBeat_ACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_HeartBeat_ACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_HeartBeat_ACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_HeartBeat_ACK));
  MESSAGEID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Message_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_HeartBeat_SYN_descriptor_, &MSG_HeartBeat_SYN::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_HeartBeat_ACK_descriptor_, &MSG_HeartBeat_ACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Message_2eproto() {
  delete MSG_HeartBeat_SYN::default_instance_;
  delete MSG_HeartBeat_SYN_reflection_;
  delete MSG_HeartBeat_ACK::default_instance_;
  delete MSG_HeartBeat_ACK_reflection_;
}

void protobuf_AddDesc_Message_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rMessage.proto\"=\n\021MSG_HeartBeat_SYN\022(\n\005"
    "msgid\030\001 \001(\0162\n.MESSAGEID:\rHEARTBEAT_SYN\"="
    "\n\021MSG_HeartBeat_ACK\022(\n\005msgid\030\001 \001(\0162\n.MES"
    "SAGEID:\rHEARTBEAT_ACK*1\n\tMESSAGEID\022\021\n\rHE"
    "ARTBEAT_SYN\020\000\022\021\n\rHEARTBEAT_ACK\020\001", 192);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Message.proto", &protobuf_RegisterTypes);
  MSG_HeartBeat_SYN::default_instance_ = new MSG_HeartBeat_SYN();
  MSG_HeartBeat_ACK::default_instance_ = new MSG_HeartBeat_ACK();
  MSG_HeartBeat_SYN::default_instance_->InitAsDefaultInstance();
  MSG_HeartBeat_ACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Message_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Message_2eproto {
  StaticDescriptorInitializer_Message_2eproto() {
    protobuf_AddDesc_Message_2eproto();
  }
} static_descriptor_initializer_Message_2eproto_;
const ::google::protobuf::EnumDescriptor* MESSAGEID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MESSAGEID_descriptor_;
}
bool MESSAGEID_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int MSG_HeartBeat_SYN::kMsgidFieldNumber;
#endif  // !_MSC_VER

MSG_HeartBeat_SYN::MSG_HeartBeat_SYN()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_HeartBeat_SYN::InitAsDefaultInstance() {
}

MSG_HeartBeat_SYN::MSG_HeartBeat_SYN(const MSG_HeartBeat_SYN& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_HeartBeat_SYN::SharedCtor() {
  _cached_size_ = 0;
  msgid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_HeartBeat_SYN::~MSG_HeartBeat_SYN() {
  SharedDtor();
}

void MSG_HeartBeat_SYN::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MSG_HeartBeat_SYN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_HeartBeat_SYN::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_HeartBeat_SYN_descriptor_;
}

const MSG_HeartBeat_SYN& MSG_HeartBeat_SYN::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Message_2eproto();
  return *default_instance_;
}

MSG_HeartBeat_SYN* MSG_HeartBeat_SYN::default_instance_ = NULL;

MSG_HeartBeat_SYN* MSG_HeartBeat_SYN::New() const {
  return new MSG_HeartBeat_SYN;
}

void MSG_HeartBeat_SYN::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    msgid_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_HeartBeat_SYN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_SYN];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MESSAGEID_IsValid(value)) {
            set_msgid(static_cast< ::MESSAGEID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_HeartBeat_SYN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_SYN];
  if (has_msgid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_HeartBeat_SYN::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_SYN];
  if (has_msgid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_HeartBeat_SYN::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_SYN];
    if (has_msgid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_HeartBeat_SYN::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_HeartBeat_SYN* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_HeartBeat_SYN*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_HeartBeat_SYN::MergeFrom(const MSG_HeartBeat_SYN& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgid()) {
      set_msgid(from.msgid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_HeartBeat_SYN::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_HeartBeat_SYN::CopyFrom(const MSG_HeartBeat_SYN& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_HeartBeat_SYN::IsInitialized() const {

  return true;
}

void MSG_HeartBeat_SYN::Swap(MSG_HeartBeat_SYN* other) {
  if (other != this) {
    std::swap(msgid_, other->msgid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_HeartBeat_SYN::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_HeartBeat_SYN_descriptor_;
  metadata.reflection = MSG_HeartBeat_SYN_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MSG_HeartBeat_ACK::kMsgidFieldNumber;
#endif  // !_MSC_VER

MSG_HeartBeat_ACK::MSG_HeartBeat_ACK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_HeartBeat_ACK::InitAsDefaultInstance() {
}

MSG_HeartBeat_ACK::MSG_HeartBeat_ACK(const MSG_HeartBeat_ACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_HeartBeat_ACK::SharedCtor() {
  _cached_size_ = 0;
  msgid_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_HeartBeat_ACK::~MSG_HeartBeat_ACK() {
  SharedDtor();
}

void MSG_HeartBeat_ACK::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MSG_HeartBeat_ACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_HeartBeat_ACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_HeartBeat_ACK_descriptor_;
}

const MSG_HeartBeat_ACK& MSG_HeartBeat_ACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Message_2eproto();
  return *default_instance_;
}

MSG_HeartBeat_ACK* MSG_HeartBeat_ACK::default_instance_ = NULL;

MSG_HeartBeat_ACK* MSG_HeartBeat_ACK::New() const {
  return new MSG_HeartBeat_ACK;
}

void MSG_HeartBeat_ACK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    msgid_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_HeartBeat_ACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_ACK];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MESSAGEID_IsValid(value)) {
            set_msgid(static_cast< ::MESSAGEID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_HeartBeat_ACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_ACK];
  if (has_msgid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_HeartBeat_ACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_ACK];
  if (has_msgid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_HeartBeat_ACK::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .MESSAGEID msgid = 1 [default = HEARTBEAT_ACK];
    if (has_msgid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_HeartBeat_ACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_HeartBeat_ACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_HeartBeat_ACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_HeartBeat_ACK::MergeFrom(const MSG_HeartBeat_ACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgid()) {
      set_msgid(from.msgid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_HeartBeat_ACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_HeartBeat_ACK::CopyFrom(const MSG_HeartBeat_ACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_HeartBeat_ACK::IsInitialized() const {

  return true;
}

void MSG_HeartBeat_ACK::Swap(MSG_HeartBeat_ACK* other) {
  if (other != this) {
    std::swap(msgid_, other->msgid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_HeartBeat_ACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_HeartBeat_ACK_descriptor_;
  metadata.reflection = MSG_HeartBeat_ACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
